Vsebp 52 as a user i want to be able to see detailed information for a specific event such that i can have an overview of that event
via-bachelor-a23-michael-kutaiba-kasper/BPR-App pull request #9
Opened 2023-12-01 14:41 UTC by Kasper-S-Jensen

- implement frontend for multiple user stories including:
See detailed event information
Create event
See all current events

all user stories are complete with validation and tests

2023-12-01 14:47 UTC, michaelbui99 commented on app/src/main/java/io/github/viabachelora23michaelkutaibakasper/bprapp/data/repository/EventRepository.kt
> +    fun parseUtcStringToLocalDateTime(utcString: String): LocalDateTime {
Move to util or make extension method

2023-12-01 15:04 UTC, michaelbui99 requested changes
Noice 🚀

2023-12-01 15:04 UTC, michaelbui99 commented on app/src/main/java/io/github/viabachelora23michaelkutaibakasper/bprapp/ui/screens/events/createevent/TitleAndDescriptionScreen.kt
> +                    if (isInvalidTitle(title) || isInvalidDescription(description)) {
Use properties from viewmodel

2023-12-02 08:03 UTC, Kasper-S-Jensen commented on app/src/main/java/io/github/viabachelora23michaelkutaibakasper/bprapp/data/repository/EventRepository.kt
> +    fun parseUtcStringToLocalDateTime(utcString: String): LocalDateTime {
done

2023-12-02 08:05 UTC, Kasper-S-Jensen commented on app/src/main/java/io/github/viabachelora23michaelkutaibakasper/bprapp/ui/screens/events/MapView.kt
> +                    LatLng(55.862207, 9.844651),
done

2023-12-02 09:18 UTC, Kutaiba-Nezar-Kashmar approved these changes
🚀🚀 nicely done !!

2023-12-02 14:54 UTC, michaelbui99 approved these changes

2023-12-02 14:54 UTC, merged